#!/bin/bash
# ------------------------------------------------------------ #
# Script toggles Krohnkite KWin script status (enable/disable) #
# ------------------------------------------------------------ #

# check if script is active
krohnkite_status=`cat ~/.config/kwinrc | grep krohnkiteEnabled= | rev | cut -d"=" -f1 | rev`

# select new status
if $krohnkite_status; then
    new_status=false
else
    new_status=true
fi

# toggle script status
kwriteconfig5 --file kwinrc --group Plugins --key krohnkiteEnabled $new_status
qdbus org.kde.KWin /KWin reconfigure
